---
title: "README for Exploratory Data Week 1 assignment"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

set the present working directory
```{r results='hide'}
setwd("/Users/zliu11/R_for_DScourses/Course4.ExpDataAnalysis/week1project/Repo_for_wk1_proj")
```

load library

```{r results='hide', message=FALSE, error=FALSE}
library(data.table)
```

download the data file and unzip it to the same folder

```{r results='hide', message=FALSE, error=FALSE}
dataUrl = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(dataUrl, destfile = "elec_power_consumption.zip", method = "curl")
unzip("elec_power_consumption.zip")
```

read data spanning 1/2/2007 to 2/2/2007 to the data table called "dt" while keeping the original column names

```{r}
dt <- fread("household_power_consumption.txt", skip = "1/2/2007", nrows = 2880, col.names = colnames(fread("household_power_consumption.txt", nrows = 1)))

dt
```

Combine date and time to generate another column, then convert them into date/time class

```{r}
dt[, date.time := paste(dt$Date, dt$Time, sep = " ")]
DateTime <- dt$date.time
DateTime <- as.POSIXct(DateTime, format = "%d/%m/%Y %H:%M:%S")
dt$date.time <- DateTime
```

# plot1

```{r message=FALSE, error=FALSE}
hist(dt$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red")
dev.copy(png, file = "plot1.png")
dev.off()
```

# plot2

```{r}
with(dt, {plot(Global_active_power ~ date.time, type = "l", ylab = "Global Active Power (kilowatts)", xlab="")})
dev.copy(png, file = "plot2.png")
dev.off()
```

# plot3

```{r}
with(dt, {plot(Sub_metering_1 ~ date.time, type = "l", ylab = "Energy sub metering", xlab = "") 
        lines(Sub_metering_2 ~ date.time, col = "red")
        lines(Sub_metering_3 ~ date.time, col = "blue")
})

legend("topright", col = c("black", "red", "blue"), lty = 1, lwd = 2, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))

dev.copy(png, file = "plot3.png")
dev.off()
```

# plot4

```{r}
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(dt, {
  plot(Global_active_power~date.time, type="l", 
       ylab="Global Active Power", xlab="")
  plot(Voltage~date.time, type="l", 
       ylab="Voltage", xlab = "datetime")
  plot(Sub_metering_1~date.time, type="l", 
       ylab="Energy sub metering", xlab="")
  lines(Sub_metering_2~date.time,col='red')
  lines(Sub_metering_3~date.time,col='blue')
  legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",
         legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  plot(Global_reactive_power~date.time, type="l", 
       ylab="Global_rective_power",xlab="datetime")
})

dev.copy(png, file = "plot4.png")
dev.off()
```

